### ISSUE TITLE
Fails in IJ 13

### ISSUE THREAD

**Issue by MikeMitterer** [denis-zhdanov/intellij-plugin-export-keymap#15]
It crashes with:
PluginException: cannot create class "org.intellij.plugins.export.keymap.ExportKeymapAction" [Plugin: Keymap exporter]: cannot create class "org.intellij.plugins.export.keymap.ExportKeymapAction" [Plugin: Keymap exporter]

Throwable: Null child action in group Tools () of class class com.intellij.openapi.actionSystem.DefaultCompactActionGroup, id=ExportKeymap

**Comment by dmimat** [comment]
Fixed in version 2.0
